In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.io as pio

In [2]:
dataset=pd.read_csv("Lead_Scoring_Regression.csv")

In [3]:
dataset

,Lead_ID,Lead_Source,Industry,Total_Visits,Time_Spent_Website,Page_Views,Email_Opens,Email_Clicks,Previous_Interactions,Lead_Quality_Score,Age,Annual_Income,Sales_Calls,Days_Since_Last_Activity,Estimated_Lead_Value
0,10001,Website,IT,4.0,1408.0,4.93,11.0,6,12,20.66,43,65285.0,13,93,76395.09
1,10002,Referral,Manufacturing,3.0,514.0,6.95,15.0,9,15,78.89,41,91555.0,2,69,103479.70
2,10003,LinkedIn,Finance,13.0,NaN,13.09,13.0,2,0,32.17,33,142713.0,2,117,72876.96
3,10004,Referral,Healthcare,23.0,73.0,8.57,15.0,4,5,92.98,57,57471.0,3,9,104055.36
4,10005,Referral,Finance,9.0,600.0,1.13,7.0,6,12,91.42,46,73671.0,8,126,104722.27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1785,11796,Website,Education,13.0,1159.0,9.11,14.0,7,10,80.53,39,NaN,1,68,112770.55
1786,11797,Email,Retail,30.0,1428.0,13.33,0.0,6,7,44.76,49,30037.0,5,171,84872.35
1787,11798,Google,Manufacturing,7.0,727.0,14.82,15.0,1,6,93.77,30,85526.0,12,73,111880.49
1788,11799,Facebook,Healthcare,26.0,1152.0,13.04,4.0,0,7,72.54,32,NaN,11,6,129093.92
1789,11800,Email,Finance,20.0,623.0,3.67,2.0,6,11,54.91,50,39693.0,5,15,96272.33

In [19]:
dataset = dataset.drop('Lead_ID', axis=1, errors='ignore')
dataset

,Lead_Source,Industry,Total_Visits,Time_Spent_Website,Page_Views,Email_Opens,Email_Clicks,Previous_Interactions,Lead_Quality_Score,Age,Annual_Income,Sales_Calls,Days_Since_Last_Activity,Estimated_Lead_Value
0,Website,IT,4.0,1408.0,4.93,11.0,6,12,20.66,43,65285.0,13,93,76395.09
1,Referral,Manufacturing,3.0,514.0,6.95,15.0,9,15,78.89,41,91555.0,2,69,103479.70
2,LinkedIn,Finance,13.0,NaN,13.09,13.0,2,0,32.17,33,142713.0,2,117,72876.96
3,Referral,Healthcare,23.0,73.0,8.57,15.0,4,5,92.98,57,57471.0,3,9,104055.36
4,Referral,Finance,9.0,600.0,1.13,7.0,6,12,91.42,46,73671.0,8,126,104722.27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1785,Website,Education,13.0,1159.0,9.11,14.0,7,10,80.53,39,NaN,1,68,112770.55
1786,Email,Retail,30.0,1428.0,13.33,0.0,6,7,44.76,49,30037.0,5,171,84872.35
1787,Google,Manufacturing,7.0,727.0,14.82,15.0,1,6,93.77,30,85526.0,12,73,111880.49
1788,Facebook,Healthcare,26.0,1152.0,13.04,4.0,0,7,72.54,32,NaN,11,6,129093.92
1789,Email,Finance,20.0,623.0,3.67,2.0,6,11,54.91,50,39693.0,5,15,96272.33

In [20]:
independent = dataset.drop('Estimated_Lead_Value', axis=1)

In [21]:
independent

,Lead_Source,Industry,Total_Visits,Time_Spent_Website,Page_Views,Email_Opens,Email_Clicks,Previous_Interactions,Lead_Quality_Score,Age,Annual_Income,Sales_Calls,Days_Since_Last_Activity
0,Website,IT,4.0,1408.0,4.93,11.0,6,12,20.66,43,65285.0,13,93
1,Referral,Manufacturing,3.0,514.0,6.95,15.0,9,15,78.89,41,91555.0,2,69
2,LinkedIn,Finance,13.0,NaN,13.09,13.0,2,0,32.17,33,142713.0,2,117
3,Referral,Healthcare,23.0,73.0,8.57,15.0,4,5,92.98,57,57471.0,3,9
4,Referral,Finance,9.0,600.0,1.13,7.0,6,12,91.42,46,73671.0,8,126
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1785,Website,Education,13.0,1159.0,9.11,14.0,7,10,80.53,39,NaN,1,68
1786,Email,Retail,30.0,1428.0,13.33,0.0,6,7,44.76,49,30037.0,5,171
1787,Google,Manufacturing,7.0,727.0,14.82,15.0,1,6,93.77,30,85526.0,12,73
1788,Facebook,Healthcare,26.0,1152.0,13.04,4.0,0,7,72.54,32,NaN,11,6
1789,Email,Finance,20.0,623.0,3.67,2.0,6,11,54.91,50,39693.0,5,15

In [22]:
dependent = dataset['Estimated_Lead_Value']

In [23]:
dependent

0        76395.09
1       103479.70
2        72876.96
3       104055.36
4       104722.27
          ...
1785    112770.55
1786     84872.35
1787    111880.49
1788    129093.92
1789     96272.33
Name: Estimated_Lead_Value, Length: 1790, dtype: float64

In [24]:
def quanQual(dataset):
    quan = []
    qual = []

    for column in dataset.columns:
        if dataset[column].dtype == 'object':
            qual.append(column)
        else:
            quan.append(column)

    return quan, qual

In [25]:
quan, qual = quanQual(independent)

In [26]:
print("Quantitative columns:")
print(quan)

print("\nQualitative columns:")
print(qual)

Quantitative columns:
['Total_Visits', 'Time_Spent_Website', 'Page_Views', 'Email_Opens', 'Email_Clicks', 'Previous_Interactions', 'Lead_Quality_Score', 'Age', 'Annual_Income', 'Sales_Calls', 'Days_Since_Last_Activity']

Qualitative columns:
['Lead_Source', 'Industry']

In [27]:
independent = pd.get_dummies(
    independent,
    columns=qual,
    drop_first=True,
    dtype=int
)

In [28]:
independent

,Total_Visits,Time_Spent_Website,Page_Views,Email_Opens,Email_Clicks,Previous_Interactions,Lead_Quality_Score,Age,Annual_Income,Sales_Calls,...,Lead_Source_Facebook,Lead_Source_Google,Lead_Source_LinkedIn,Lead_Source_Referral,Lead_Source_Website,Industry_Finance,Industry_Healthcare,Industry_IT,Industry_Manufacturing,Industry_Retail
0,4.0,1408.0,4.93,11.0,6,12,20.66,43,65285.0,13,...,0,0,0,0,1,0,0,1,0,0
1,3.0,514.0,6.95,15.0,9,15,78.89,41,91555.0,2,...,0,0,0,1,0,0,0,0,1,0
2,13.0,NaN,13.09,13.0,2,0,32.17,33,142713.0,2,...,0,0,1,0,0,1,0,0,0,0
3,23.0,73.0,8.57,15.0,4,5,92.98,57,57471.0,3,...,0,0,0,1,0,0,1,0,0,0
4,9.0,600.0,1.13,7.0,6,12,91.42,46,73671.0,8,...,0,0,0,1,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1785,13.0,1159.0,9.11,14.0,7,10,80.53,39,NaN,1,...,0,0,0,0,1,0,0,0,0,0
1786,30.0,1428.0,13.33,0.0,6,7,44.76,49,30037.0,5,...,0,0,0,0,0,0,0,0,0,1
1787,7.0,727.0,14.82,15.0,1,6,93.77,30,85526.0,12,...,0,1,0,0,0,0,0,0,1,0
1788,26.0,1152.0,13.04,4.0,0,7,72.54,32,NaN,11,...,1,0,0,0,0,0,1,0,0,0
1789,20.0,623.0,3.67,2.0,6,11,54.91,50,39693.0,5,...,0,0,0,0,0,1,0,0,0,0

In [29]:
descriptive=pd.DataFrame()

In [32]:
descriptive = pd.DataFrame(index=["Mean", "Median", "Mode"], columns=quan)

for columnName in quan:
    descriptive.loc["Mean", columnName] = dataset[columnName].mean()
    descriptive.loc["Median", columnName] = dataset[columnName].median()
    descriptive.loc["Mode", columnName] = dataset[columnName].mode()[0]

In [34]:
descriptive

,Total_Visits,Time_Spent_Website,Page_Views,Email_Opens,Email_Clicks,Previous_Interactions,Lead_Quality_Score,Age,Annual_Income,Sales_Calls,Days_Since_Last_Activity
Mean,15.606838,778.788034,10.395721,9.956125,5.07486,7.558659,60.528001,39.796648,87643.717379,7.560894,90.165922
Median,16.0,791.0,10.45,10.0,5.0,8.0,60.515,40.0,86829.0,7.0,90.0
Mode,17.0,1290.0,5.19,0.0,6,15,58.02,35,53688.0,15,179

In [35]:
descriptive = pd.DataFrame(index=["Mean", "Median", "Mode","Q1:25%","Q2:50%","Q3:75%","Q4:100%"], columns=quan)
for columnName in quan:
    descriptive.loc["Mean", columnName] = dataset[columnName].mean()
    descriptive.loc["Median", columnName] = dataset[columnName].median()
    descriptive.loc["Mode", columnName] = dataset[columnName].mode()[0]
    descriptive.loc["Q1:25%", columnName] = dataset.describe()[columnName]["25%"]
    descriptive.loc["Q2:50%", columnName] = dataset.describe()[columnName]["50%"]
    descriptive.loc["Q3:75%", columnName] = dataset.describe()[columnName]["75%"]
    descriptive.loc["Q4:100%", columnName] = dataset.describe()[columnName]["max"]

In [36]:
descriptive

,Total_Visits,Time_Spent_Website,Page_Views,Email_Opens,Email_Clicks,Previous_Interactions,Lead_Quality_Score,Age,Annual_Income,Sales_Calls,Days_Since_Last_Activity
Mean,15.606838,778.788034,10.395721,9.956125,5.07486,7.558659,60.528001,39.796648,87643.717379,7.560894,90.165922
Median,16.0,791.0,10.45,10.0,5.0,8.0,60.515,40.0,86829.0,7.0,90.0
Mode,17.0,1290.0,5.19,0.0,6,15,58.02,35,53688.0,15,179
Q1:25%,8.0,413.5,5.585,5.0,2.0,4.0,40.63,29.0,56989.5,4.0,46.0
Q2:50%,16.0,791.0,10.45,10.0,5.0,8.0,60.515,40.0,86829.0,7.0,90.0
Q3:75%,23.0,1146.0,15.145,15.0,8.0,12.0,80.6075,50.0,119277.0,12.0,135.0
Q4:100%,30.0,1499.0,20.0,20.0,10.0,15.0,99.97,60.0,150000.0,15.0,180.0

In [37]:
descriptive = pd.DataFrame(index=["Mean", "Median", "Mode","Q1:25%","Q2:50%","Q3:75%","Q4:100%","IQR","1.5rule","Lesser","Greater","Min","Max"],columns=quan)
for columnName in quan:
    descriptive.loc["Mean", columnName] = dataset[columnName].mean()
    descriptive.loc["Median", columnName] = dataset[columnName].median()
    descriptive.loc["Mode", columnName] = dataset[columnName].mode()[0]
    descriptive.loc["Q1:25%", columnName] = dataset.describe()[columnName]["25%"]
    descriptive.loc["Q2:50%", columnName] = dataset.describe()[columnName]["50%"]
    descriptive.loc["Q3:75%", columnName] = dataset.describe()[columnName]["75%"]
    descriptive.loc["Q4:100%", columnName] = dataset.describe()[columnName]["max"]
    descriptive.loc["IQR", columnName] = descriptive.loc["Q3:75%", columnName]-descriptive.loc["Q1:25%", columnName]
    descriptive.loc["1.5rule", columnName] = 1.5*descriptive.loc["IQR", columnName]
    descriptive.loc["Lesser", columnName] = descriptive.loc["Q1:25%", columnName]-1.5*descriptive.loc["IQR", columnName]
    descriptive.loc["Greater", columnName] = descriptive.loc["Q3:75%", columnName]+1.5*descriptive.loc["IQR", columnName]
    descriptive.loc["Min", columnName] = dataset[columnName].min()
    descriptive.loc["Max", columnName] = dataset[columnName].max()

In [38]:
descriptive

,Total_Visits,Time_Spent_Website,Page_Views,Email_Opens,Email_Clicks,Previous_Interactions,Lead_Quality_Score,Age,Annual_Income,Sales_Calls,Days_Since_Last_Activity
Mean,15.606838,778.788034,10.395721,9.956125,5.07486,7.558659,60.528001,39.796648,87643.717379,7.560894,90.165922
Median,16.0,791.0,10.45,10.0,5.0,8.0,60.515,40.0,86829.0,7.0,90.0
Mode,17.0,1290.0,5.19,0.0,6,15,58.02,35,53688.0,15,179
Q1:25%,8.0,413.5,5.585,5.0,2.0,4.0,40.63,29.0,56989.5,4.0,46.0
Q2:50%,16.0,791.0,10.45,10.0,5.0,8.0,60.515,40.0,86829.0,7.0,90.0
Q3:75%,23.0,1146.0,15.145,15.0,8.0,12.0,80.6075,50.0,119277.0,12.0,135.0
Q4:100%,30.0,1499.0,20.0,20.0,10.0,15.0,99.97,60.0,150000.0,15.0,180.0
IQR,15.0,732.5,9.56,10.0,6.0,8.0,39.9775,21.0,62287.5,8.0,89.0
1.5rule,22.5,1098.75,14.34,15.0,9.0,12.0,59.96625,31.5,93431.25,12.0,133.5
Lesser,-14.5,-685.25,-8.755,-10.0,-7.0,-8.0,-19.33625,-2.5,-36441.75,-8.0,-87.5
Greater,45.5,2244.75,29.485,30.0,17.0,24.0,140.57375,81.5,212708.25,24.0,268.5
Min,1.0,30.0,1.01,0.0,0,0,20.08,21,25042.0,0,1
Max,30.0,1499.0,20.0,20.0,10,15,99.97,60,150000.0,15,180

In [40]:
lesser=[]
greater=[]

for columnName in quan:
    if(descriptive[columnName]["Min"]<descriptive[columnName]["Lesser"]):
       lesser.append(columnName)
    if(descriptive[columnName]["Max"]>descriptive[columnName]["Greater"]):
       greater.append(columnName)

In [41]:
lesser

[]

In [42]:
greater

[]

In [43]:
for columnName in lesser:
    dataset.loc[dataset[columnName] < descriptive.loc["Lesser", columnName],columnName] = descriptive.loc["Lesser", columnName]
for columnName in greater:
    dataset.loc[dataset[columnName] > descriptive.loc["Greater", columnName],columnName] = descriptive.loc["Greater", columnName]

In [44]:
descriptive = pd.DataFrame(index=["Mean", "Median", "Mode","Q1:25%","Q2:50%","Q3:75%","Q4:100%","IQR","1.5rule","Lesser","Greater","Min","Max"],columns=quan)
for columnName in quan:
    descriptive.loc["Mean", columnName] = dataset[columnName].mean()
    descriptive.loc["Median", columnName] = dataset[columnName].median()
    descriptive.loc["Mode", columnName] = dataset[columnName].mode()[0]
    descriptive.loc["Q1:25%", columnName] = dataset.describe()[columnName]["25%"]
    descriptive.loc["Q2:50%", columnName] = dataset.describe()[columnName]["50%"]
    descriptive.loc["Q3:75%", columnName] = dataset.describe()[columnName]["75%"]
    descriptive.loc["Q4:100%", columnName] = dataset.describe()[columnName]["max"]
    descriptive.loc["IQR", columnName] = descriptive.loc["Q3:75%", columnName]-descriptive.loc["Q1:25%", columnName]
    descriptive.loc["1.5rule", columnName] = 1.5*descriptive.loc["IQR", columnName]
    descriptive.loc["Lesser", columnName] = descriptive.loc["Q1:25%", columnName]-1.5*descriptive.loc["IQR", columnName]
    descriptive.loc["Greater", columnName] = descriptive.loc["Q3:75%", columnName]+1.5*descriptive.loc["IQR", columnName]
    descriptive.loc["Min", columnName] = dataset[columnName].min()
    descriptive.loc["Max", columnName] = dataset[columnName].max()

In [45]:
descriptive

,Total_Visits,Time_Spent_Website,Page_Views,Email_Opens,Email_Clicks,Previous_Interactions,Lead_Quality_Score,Age,Annual_Income,Sales_Calls,Days_Since_Last_Activity
Mean,15.606838,778.788034,10.395721,9.956125,5.07486,7.558659,60.528001,39.796648,87643.717379,7.560894,90.165922
Median,16.0,791.0,10.45,10.0,5.0,8.0,60.515,40.0,86829.0,7.0,90.0
Mode,17.0,1290.0,5.19,0.0,6,15,58.02,35,53688.0,15,179
Q1:25%,8.0,413.5,5.585,5.0,2.0,4.0,40.63,29.0,56989.5,4.0,46.0
Q2:50%,16.0,791.0,10.45,10.0,5.0,8.0,60.515,40.0,86829.0,7.0,90.0
Q3:75%,23.0,1146.0,15.145,15.0,8.0,12.0,80.6075,50.0,119277.0,12.0,135.0
Q4:100%,30.0,1499.0,20.0,20.0,10.0,15.0,99.97,60.0,150000.0,15.0,180.0
IQR,15.0,732.5,9.56,10.0,6.0,8.0,39.9775,21.0,62287.5,8.0,89.0
1.5rule,22.5,1098.75,14.34,15.0,9.0,12.0,59.96625,31.5,93431.25,12.0,133.5
Lesser,-14.5,-685.25,-8.755,-10.0,-7.0,-8.0,-19.33625,-2.5,-36441.75,-8.0,-87.5
Greater,45.5,2244.75,29.485,30.0,17.0,24.0,140.57375,81.5,212708.25,24.0,268.5
Min,1.0,30.0,1.01,0.0,0,0,20.08,21,25042.0,0,1
Max,30.0,1499.0,20.0,20.0,10,15,99.97,60,150000.0,15,180

In [46]:
lesser=[]
greater=[]

for columnName in quan:
    if(descriptive[columnName]["Lesser"]>descriptive[columnName]["Min"]):
        lesser.append(columnName)
    if(descriptive[columnName]["Greater"]<descriptive[columnName]["Max"]):
        greater.append(columnName)

In [47]:
lesser

[]

In [48]:
greater

[]

In [49]:
freqTable=pd.DataFrame(columns=["Unique_Values","Frequency","Relative Frequency","Cusum"])

In [50]:
freqTable

Empty DataFrame
Columns: [Unique_Values, Frequency, Relative Frequency, Cusum]
Index: []

In [51]:
freqTable["Unique_Values"]=dataset["Lead_Quality_Score"].value_counts().index
freqTable["Frequency"]=dataset["Lead_Quality_Score"].value_counts().values
freqTable["Relative Frequency"]=(freqTable["Frequency"]/103)
freqTable["Cusum"]=freqTable["Relative Frequency"].cumsum()

In [52]:
freqTable

      Unique_Values  Frequency  Relative Frequency      Cusum
0             58.02          4            0.038835   0.038835
1             21.62          3            0.029126   0.067961
2             90.00          3            0.029126   0.097087
3             88.64          3            0.029126   0.126214
4             88.24          3            0.029126   0.155340
...             ...        ...                 ...        ...
1576          95.61          1            0.009709  17.009709
1577          91.54          1            0.009709  17.019417
1578          65.75          1            0.009709  17.029126
1579          41.24          1            0.009709  17.038835
1580          54.91          1            0.009709  17.048544

[1581 rows x 4 columns]

In [53]:
def Univariate(dataset,quan):
    descriptive = pd.DataFrame(index=["Mean", "Median", "Mode","Q1:25%","Q2:50%","Q3:75%","Q4:100%","IQR","1.5rule","Lesser","Greater","Min","Max"],columns=quan)
    for columnName in quan:
    
        descriptive.loc["Mean", columnName] = dataset[columnName].mean()
        descriptive.loc["Median", columnName] = dataset[columnName].median()
        descriptive.loc["Mode", columnName] = dataset[columnName].mode()[0]
        descriptive.loc["Q1:25%", columnName] = dataset.describe()[columnName]["25%"]
        descriptive.loc["Q2:50%", columnName] = dataset.describe()[columnName]["50%"]
        descriptive.loc["Q3:75%", columnName] = dataset.describe()[columnName]["75%"]
        descriptive.loc["Q4:100%", columnName] = dataset.describe()[columnName]["max"]
        descriptive.loc["IQR", columnName] = descriptive.loc["Q3:75%", columnName]-descriptive.loc["Q1:25%", columnName]
        descriptive.loc["1.5rule", columnName] = 1.5*descriptive.loc["IQR", columnName]
        descriptive.loc["Lesser", columnName] = descriptive.loc["Q1:25%", columnName]-1.5*descriptive.loc["IQR", columnName]
        descriptive.loc["Greater", columnName] = descriptive.loc["Q3:75%", columnName]+1.5*descriptive.loc["IQR", columnName]
        descriptive.loc["Min", columnName] = dataset[columnName].min()
        descriptive.loc["Max", columnName] = dataset[columnName].max()      
    
    return descriptive

In [54]:
Univariate(dataset,quan)

,Total_Visits,Time_Spent_Website,Page_Views,Email_Opens,Email_Clicks,Previous_Interactions,Lead_Quality_Score,Age,Annual_Income,Sales_Calls,Days_Since_Last_Activity
Mean,15.606838,778.788034,10.395721,9.956125,5.07486,7.558659,60.528001,39.796648,87643.717379,7.560894,90.165922
Median,16.0,791.0,10.45,10.0,5.0,8.0,60.515,40.0,86829.0,7.0,90.0
Mode,17.0,1290.0,5.19,0.0,6,15,58.02,35,53688.0,15,179
Q1:25%,8.0,413.5,5.585,5.0,2.0,4.0,40.63,29.0,56989.5,4.0,46.0
Q2:50%,16.0,791.0,10.45,10.0,5.0,8.0,60.515,40.0,86829.0,7.0,90.0
Q3:75%,23.0,1146.0,15.145,15.0,8.0,12.0,80.6075,50.0,119277.0,12.0,135.0
Q4:100%,30.0,1499.0,20.0,20.0,10.0,15.0,99.97,60.0,150000.0,15.0,180.0
IQR,15.0,732.5,9.56,10.0,6.0,8.0,39.9775,21.0,62287.5,8.0,89.0
1.5rule,22.5,1098.75,14.34,15.0,9.0,12.0,59.96625,31.5,93431.25,12.0,133.5
Lesser,-14.5,-685.25,-8.755,-10.0,-7.0,-8.0,-19.33625,-2.5,-36441.75,-8.0,-87.5
Greater,45.5,2244.75,29.485,30.0,17.0,24.0,140.57375,81.5,212708.25,24.0,268.5
Min,1.0,30.0,1.01,0.0,0,0,20.08,21,25042.0,0,1
Max,30.0,1499.0,20.0,20.0,10,15,99.97,60,150000.0,15,180

In [55]:
def Univariate(dataset,quan):
    descriptive = pd.DataFrame(index=["Mean", "Median", "Mode","Q1:25%","Q2:50%","Q3:75%","Q4:100%","IQR","1.5rule","Lesser","Greater","Min","Max","kurtosis","skew"],columns=quan)
    
    for columnName in quan:
    
        descriptive.loc["Mean", columnName] = dataset[columnName].mean()
        descriptive.loc["Median", columnName] = dataset[columnName].median()
        descriptive.loc["Mode", columnName] = dataset[columnName].mode()[0]
        descriptive.loc["Q1:25%", columnName] = dataset.describe()[columnName]["25%"]
        descriptive.loc["Q2:50%", columnName] = dataset.describe()[columnName]["50%"]
        descriptive.loc["Q3:75%", columnName] = dataset.describe()[columnName]["75%"]
        descriptive.loc["Q4:100%", columnName] = dataset.describe()[columnName]["max"]
        descriptive.loc["IQR", columnName] = descriptive.loc["Q3:75%", columnName]-descriptive.loc["Q1:25%", columnName]
        descriptive.loc["1.5rule", columnName] = 1.5*descriptive.loc["IQR", columnName]
        descriptive.loc["Lesser", columnName] = descriptive.loc["Q1:25%", columnName]-1.5*descriptive.loc["IQR", columnName]
        descriptive.loc["Greater", columnName] = descriptive.loc["Q3:75%", columnName]+1.5*descriptive.loc["IQR", columnName]
        descriptive.loc["Min", columnName] = dataset[columnName].min()
        descriptive.loc["Max", columnName] = dataset[columnName].max()    
        descriptive.loc["kurtosis", columnName] = dataset[columnName].kurtosis()
        descriptive.loc["skew", columnName] = dataset[columnName].skew()
        
    return descriptive

In [56]:
Univariate(dataset,quan)

,Total_Visits,Time_Spent_Website,Page_Views,Email_Opens,Email_Clicks,Previous_Interactions,Lead_Quality_Score,Age,Annual_Income,Sales_Calls,Days_Since_Last_Activity
Mean,15.606838,778.788034,10.395721,9.956125,5.07486,7.558659,60.528001,39.796648,87643.717379,7.560894,90.165922
Median,16.0,791.0,10.45,10.0,5.0,8.0,60.515,40.0,86829.0,7.0,90.0
Mode,17.0,1290.0,5.19,0.0,6,15,58.02,35,53688.0,15,179
Q1:25%,8.0,413.5,5.585,5.0,2.0,4.0,40.63,29.0,56989.5,4.0,46.0
Q2:50%,16.0,791.0,10.45,10.0,5.0,8.0,60.515,40.0,86829.0,7.0,90.0
Q3:75%,23.0,1146.0,15.145,15.0,8.0,12.0,80.6075,50.0,119277.0,12.0,135.0
Q4:100%,30.0,1499.0,20.0,20.0,10.0,15.0,99.97,60.0,150000.0,15.0,180.0
IQR,15.0,732.5,9.56,10.0,6.0,8.0,39.9775,21.0,62287.5,8.0,89.0
1.5rule,22.5,1098.75,14.34,15.0,9.0,12.0,59.96625,31.5,93431.25,12.0,133.5
Lesser,-14.5,-685.25,-8.755,-10.0,-7.0,-8.0,-19.33625,-2.5,-36441.75,-8.0,-87.5
Greater,45.5,2244.75,29.485,30.0,17.0,24.0,140.57375,81.5,212708.25,24.0,268.5
Min,1.0,30.0,1.01,0.0,0,0,20.08,21,25042.0,0,1
Max,30.0,1499.0,20.0,20.0,10,15,99.97,60,150000.0,15,180
kurtosis,-1.210872,-1.184516,-1.220473,-1.188516,-1.187668,-1.208763,-1.193859,-1.190657,-1.184809,-1.219023,-1.181668
skew,-0.035772,-0.038103,0.003689,-0.051564,-0.032882,0.000336,-0.031812,0.055558,-0.007986,0.014193,0.005917

In [57]:
def Univariate(dataset,quan):
    descriptive = pd.DataFrame(index=["Mean", "Median", "Mode","Q1:25%","Q2:50%","Q3:75%","Q4:100%","IQR","1.5rule","Lesser","Greater","Min","Max","kurtosis","skew","var","std"],columns=quan)
    for columnName in quan:
    
        descriptive.loc["Mean", columnName] = dataset[columnName].mean()
        descriptive.loc["Median", columnName] = dataset[columnName].median()
        descriptive.loc["Mode", columnName] = dataset[columnName].mode()[0]
        descriptive.loc["Q1:25%", columnName] = dataset.describe()[columnName]["25%"]
        descriptive.loc["Q2:50%", columnName] = dataset.describe()[columnName]["50%"]
        descriptive.loc["Q3:75%", columnName] = dataset.describe()[columnName]["75%"]
        descriptive.loc["Q4:100%", columnName] = dataset.describe()[columnName]["max"]
        descriptive.loc["IQR", columnName] = descriptive.loc["Q3:75%", columnName]-descriptive.loc["Q1:25%", columnName]
        descriptive.loc["1.5rule", columnName] = 1.5*descriptive.loc["IQR", columnName]
        descriptive.loc["Lesser", columnName] = descriptive.loc["Q1:25%", columnName]-1.5*descriptive.loc["IQR", columnName]
        descriptive.loc["Greater", columnName] = descriptive.loc["Q3:75%", columnName]+1.5*descriptive.loc["IQR", columnName]
        descriptive.loc["Min", columnName] = dataset[columnName].min()
        descriptive.loc["Max", columnName] = dataset[columnName].max()      
        descriptive.loc["kurtosis", columnName] = dataset[columnName].kurtosis()
        descriptive.loc["skew", columnName] = dataset[columnName].skew()
        descriptive.loc["var", columnName] = dataset[columnName].var()
        descriptive.loc["std", columnName] = dataset[columnName].std()
    return descriptive

In [58]:
Univariate(dataset,quan)

,Total_Visits,Time_Spent_Website,Page_Views,Email_Opens,Email_Clicks,Previous_Interactions,Lead_Quality_Score,Age,Annual_Income,Sales_Calls,Days_Since_Last_Activity
Mean,15.606838,778.788034,10.395721,9.956125,5.07486,7.558659,60.528001,39.796648,87643.717379,7.560894,90.165922
Median,16.0,791.0,10.45,10.0,5.0,8.0,60.515,40.0,86829.0,7.0,90.0
Mode,17.0,1290.0,5.19,0.0,6,15,58.02,35,53688.0,15,179
Q1:25%,8.0,413.5,5.585,5.0,2.0,4.0,40.63,29.0,56989.5,4.0,46.0
Q2:50%,16.0,791.0,10.45,10.0,5.0,8.0,60.515,40.0,86829.0,7.0,90.0
Q3:75%,23.0,1146.0,15.145,15.0,8.0,12.0,80.6075,50.0,119277.0,12.0,135.0
Q4:100%,30.0,1499.0,20.0,20.0,10.0,15.0,99.97,60.0,150000.0,15.0,180.0
IQR,15.0,732.5,9.56,10.0,6.0,8.0,39.9775,21.0,62287.5,8.0,89.0
1.5rule,22.5,1098.75,14.34,15.0,9.0,12.0,59.96625,31.5,93431.25,12.0,133.5
Lesser,-14.5,-685.25,-8.755,-10.0,-7.0,-8.0,-19.33625,-2.5,-36441.75,-8.0,-87.5
Greater,45.5,2244.75,29.485,30.0,17.0,24.0,140.57375,81.5,212708.25,24.0,268.5
Min,1.0,30.0,1.01,0.0,0,0,20.08,21,25042.0,0,1
Max,30.0,1499.0,20.0,20.0,10,15,99.97,60,150000.0,15,180
kurtosis,-1.210872,-1.184516,-1.220473,-1.188516,-1.187668,-1.208763,-1.193859,-1.190657,-1.184809,-1.219023,-1.181668
skew,-0.035772,-0.038103,0.003689,-0.051564,-0.032882,0.000336,-0.031812,0.055558,-0.007986,0.014193,0.005917
var,74.934275,178879.268614,30.55896,36.369226,9.678015,21.391471,531.07672,133.457786,1312948624.01244,21.77354,2658.15971
std,8.656459,422.941212,5.528016,6.03069,3.110951,4.625091,23.045102,11.552393,36234.632936,4.666213,51.557344

In [65]:
dataset= pd.read_csv("Lead_Scoring_Preprocessed.csv")

In [66]:
dataset.isnull().sum()

Lead_ID                   0
Email_Clicks              0
Previous_Interactions     0
Age                       0
Sales_Calls               0
                         ..
Annual_Income_149735.0    0
Annual_Income_149772.0    0
Annual_Income_149928.0    0
Annual_Income_150000.0    0
Annual_Income_NA          0
Length: 5579, dtype: int64